import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const read = (file) => readFileSync(new URL(`../${file}`, import.meta.url), "utf8");

test("Compose 只保留一个桌面 Profile 且不挂 Docker Socket", () => {
  const compose = read("docker-compose.yml");
  assert.match(compose, /desktop:\n/);
  assert.match(compose, /\.\/data\/browser:\/config/);
  assert.match(compose, /GPC_CDP_ALLOW:/);
  assert.match(compose, /PROFILE_AUTO_DETECT:/);
  assert.match(compose, /PROFILE_GEO_ENDPOINT:/);
  assert.match(compose, /FRAME_ACTIVE_FPS:/);
  assert.doesNotMatch(compose, /MAX_FILE_BYTES|TRANSFER_QUOTA_BYTES/);
  assert.match(compose, /user: "\$\{PUID:-1000\}:\$\{PGID:-1000\}"/);
  assert.match(compose, /- "127\.0\.0\.1:\$\{MAINTENANCE_PORT:-36091\}:8081"/);
  assert.doesNotMatch(compose, /MAINTENANCE_(?:BIND_ADDR|PUBLIC_URL|PUBLIC_PORT)/);
  assert.doesNotMatch(compose, /^\s+FRAME_FPS:/m);
  assert.doesNotMatch(compose, /^\s+FRAME_IDLE_MS:/m);
  assert.match(compose, /\.\/data-transfer:\/transfer/g);
  assert.doesNotMatch(compose, /docker\.sock/);
  assert.doesNotMatch(compose, /^\s+privileged:\s*true$/m);
  const desktopStart = compose.indexOf("\n  desktop:\n");
  const volumesStart = compose.indexOf("\nvolumes:\n", desktopStart);
  assert.ok(desktopStart >= 0 && volumesStart > desktopStart);
  const desktop = compose.slice(desktopStart, volumesStart);
  assert.match(desktop, /^    cap_add:\n      - SYS_ADMIN$/m);
  assert.doesNotMatch(`${compose.slice(0, desktopStart)}${compose.slice(volumesStart)}`, /SYS_ADMIN/);
  assert.equal((compose.match(/^  desktop:\s*$/gm) || []).length, 1);
});

test("普通入口使用 DNSPod DNS-01 的单一 HTTPS 反向代理", () => {
  const compose = read("docker-compose.yml");
  const caddyfile = read("caddy/Caddyfile");
  const dockerfile = read("caddy/Dockerfile");
  assert.match(compose, /^  https:\n/m);
  assert.match(compose, /- "0\.0\.0\.0:\$\{HTTPS_PORT:-443\}:443"/);
  assert.match(compose, /\$\{BIND_ADDR:-127\.0\.0\.1\}:\$\{HTTP_PORT:-36090\}:8080/);
  assert.match(compose, /TENCENTCLOUD_SECRET_ID: \$\{TENCENTCLOUD_SECRET_ID\?/);
  assert.match(compose, /TENCENTCLOUD_SECRET_KEY: \$\{TENCENTCLOUD_SECRET_KEY\?/);
  assert.match(compose, /HTTPS_PROXY: \$\{CADDY_PROXY_URL:-\}/);
  assert.match(compose, /NO_PROXY: gateway,localhost,127\.0\.0\.1/);
  assert.match(compose, /host\.docker\.internal:host-gateway/);
  assert.match(caddyfile, /dns tencentcloud/);
  assert.match(caddyfile, /reverse_proxy gateway:8080/);
  assert.match(caddyfile, /auto_https disable_redirects/);
  assert.match(caddyfile, /protocols h1 h2/);
  assert.doesNotMatch(caddyfile, /secret_(?:id|key)\s+[^\{]/);
  assert.match(dockerfile, /caddy:2\.11\.4-builder/);
  assert.match(dockerfile, /github\.com\/caddy-dns\/tencentcloud@v0\.4\.3/);
});

test("Docker 构建上下文排除凭据、Profile 与实验产物", () => {
  const ignored = read(".dockerignore");
  for (const path of [".env", "data", "data-panel", "data-transfer", "tmp", "node_modules"]) {
    assert.match(ignored, new RegExp(`^${path.replace(".", "\\.")}$`, "m"));
  }
});

test("桌面镜像安装 Chromium 沙箱且启动时保持启用", () => {
  const dockerfile = read("docker/Dockerfile");
  const autostart = read("docker/autostart");
  assert.match(dockerfile, /chromium-sandbox="\$\{CHROMIUM_VERSION\}"/);
  assert.doesNotMatch(autostart, /--no-sandbox|--disable-setuid-sandbox/);
});

test("启动脚本只在容器健康后打印入口", () => {
  const script = read("scripts/up.sh");
  assert.match(script, /docker compose up -d --build --wait/);
  assert.match(script, /TENCENTCLOUD_SECRET_ID:\?/);
  assert.match(script, /TENCENTCLOUD_SECRET_KEY:\?/);
  assert.match(script, /HTTPS_PORT:-443/);
  assert.ok(script.indexOf("--wait") < script.indexOf('echo "普通入口：'));
});

test("云开发预览使用动态状态且没有内置回退密码", () => {
  const cursor = read(".cursor/environment.json");
  assert.doesNotMatch(cursor, /devpass|cd gateway/);
  assert.match(cursor, /data-panel\/state\.json/);
});

test("业务代码使用动态工作区路径 Cookie", () => {
  const server = read("gateway/server.mjs");
  assert.match(server, /Path=\$\{path\}/);
  assert.match(server, /workspaceId/);
});

test("网关通过 CDP sessionId 定向输入并通过原生 Portal 选择文件", () => {
  const pkg = JSON.parse(read("package.json"));
  assert.ok(pkg.dependencies.ws);
  const cdp = read("lib/cdp.mjs");
  assert.match(cdp, /Input\.insertText/);
  assert.match(cdp, /sessionId/);
  assert.match(cdp, /Target\.createTarget/);
  assert.doesNotMatch(cdp, /Page\.bringToFront/);
  assert.match(cdp, /Emulation\.setFocusEmulationEnabled/);
  assert.match(cdp, /gpc\.workspaceId/);
  assert.match(cdp, /sessionStorage\.setItem/);
  assert.match(cdp, /Emulation\.setTimezoneOverride/);
  assert.match(cdp, /Emulation\.setLocaleOverride/);
  assert.doesNotMatch(cdp, /Network\.setExtraHTTPHeaders/);
  assert.match(cdp, /Network\.setBlockedURLs/);
  assert.match(cdp, /Network\.getResponseBody/);
  assert.match(cdp, /listChatGptProjects/);
  assert.doesNotMatch(cdp, /Fetch\./);
  assert.doesNotMatch(cdp, /DOM\.setFileInputFiles/);
  assert.doesNotMatch(cdp, /Page\.fileChooserOpened/);
  assert.doesNotMatch(cdp, /Page\.setInterceptFileChooserDialog/);
  assert.match(cdp, /fileChooserOwner/);
  assert.match(cdp, /command\.type === "selectFiles"/);
  assert.match(cdp, /command\.type === "cancelFileSelection"/);
  assert.match(cdp, /resolveUserUploads/);
  assert.doesNotMatch(cdp, /attachFiles|pendingUploads|input\[type='file'\]/);
  const portal = read("lib/portal.mjs");
  assert.match(portal, /gatewaySocket/);
  assert.match(portal, /desktopSocket/);
  assert.match(read("gateway/server.mjs"), /\/run\/gpc\/gateway\.sock/);
  assert.match(read("gateway/server.mjs"), /\/run\/gpc\/desktop\.sock/);
  assert.match(portal, /tagWorkspace/);
  assert.match(portal, /focusAdministrator/);
  const desktopPortal = read("docker/file-portal.py");
  assert.match(desktopPortal, /org\.freedesktop\.impl\.portal\.FileChooser/);
  assert.match(desktopPortal, /_GPC_WORKSPACE_ID/);
  assert.match(desktopPortal, /focus-administrator/);
  assert.match(desktopPortal, /_NET_ACTIVE_WINDOW/);
  assert.match(read("docker/gptpro-portals.conf"), /FileChooser=gpc/);
  assert.match(cdp, /Browser\.setDownloadBehavior/);
  assert.match(cdp, /Page\.startScreencast/);
  assert.match(cdp, /Page\.screencastFrameAck/);
  assert.match(cdp, /__gpcNotification/);
  assert.match(cdp, /new Proxy\(NativeNotification/);
  assert.match(cdp, /type: "notification"/);
  assert.match(cdp, /captureMode: "target-screencast"/);
  assert.match(cdp, /viewerCountsByWorkspace\(\)/);
  assert.match(cdp, /newWindow: true/);
  assert.doesNotMatch(cdp, /Page\.captureScreenshot/);
  assert.match(cdp, /activeFrameFps/);
  assert.doesNotMatch(cdp, /gpc-visual-activity|visualActiveUntil|idleFrames|heartbeatFrames/);
  assert.match(cdp, /SCREENCAST_MAX_WIDTH = 2560/);
  assert.match(cdp, /SCREENCAST_MAX_HEIGHT = 1600/);
  assert.doesNotMatch(cdp, /SCREENCAST_TIERS|streamTier|visibleWorkspaceCount/);
  assert.doesNotMatch(cdp, /Target\.activateTarget/);
  assert.match(cdp, /userAgentMetadata/);
  const focus = read("lib/focus.mjs");
  const policy = read("lib/policy.mjs");
  assert.match(focus, /projectNavigationAllowed/);
  assert.match(focus, /aside\[aria-label\*="sidebar" i\]/);
  assert.match(focus, /create-new-chat-button/);
  assert.match(focus, /button\[role="radio"\]/);
  assert.match(focus, /share-chat-button/);
  assert.match(focus, /share-chat-menu-item/);
  assert.match(focus, /share-prompt-link-turn-action-button/);
  assert.doesNotMatch(focus, /copy-turn-action-button/);
  assert.doesNotMatch(focus, /conversation-options-button/);
  assert.match(focus, /Show project details/);
  assert.match(focus, /move to project/);
  assert.match(focus, /remove from project/);
  assert.match(policy, /data-gpc-sensitive-control-hidden/);
  assert.doesNotMatch(policy, /data-gpc-sensitive-hidden/);
  assert.doesNotMatch(focus, /stopImmediatePropagation|preventDefault/);
  assert.doesNotMatch(policy, /stopImmediatePropagation|preventDefault/);
  const client = read("gateway/web/app.js");
  const server = read("gateway/server.mjs");
  const styles = read("gateway/web/app.css");
  const textInput = read("gateway/web/text-input.js");
  assert.match(client, /type: "viewerState"/);
  assert.match(client, /visibilitychange/);
  assert.doesNotMatch(client, /document\.hasFocus|addEventListener\("focus"|addEventListener\("blur"/);
  assert.match(client, /attachNativeTextInput/);
  assert.match(client, /type: "selection"/);
  assert.match(client, /type: "cut"/);
  assert.match(client, /payload\.type === "clipboard"/);
  assert.match(client, /payload\.type === "notification"/);
  assert.match(client, /class: "viewer-feedback"/);
  assert.match(client, /const PAGE_FEEDBACK_MS = 5000/);
  assert.doesNotMatch(client, /pageFeedback\.setAttribute\("role"/);
  assert.match(client, /new BrowserNotification\(title, \{ body \}\)/);
  assert.match(client, /!globalThis\.isSecureContext/);
  assert.match(client, /BrowserNotification\.permission !== "granted"/);
  assert.match(client, /BrowserNotification\.requestPermission\(\)/);
  assert.match(client, /viewer\.addEventListener\("click", requestBrowserNotifications, \{ once: true \}\)/);
  assert.doesNotMatch(client, /button\("开启浏览器通知"/);
  assert.match(client, /deliverSystemNotification\("下载完成", `\$\{payload\.file\.name\} 已保存到私人文件区`, "success"\)/);
  assert.match(client, /deliverSystemNotification\("下载失败", `\$\{payload\.file\.name\}：\$\{payload\.file\.error\}`, "error"\)/);
  assert.match(client, /deliverSystemNotification\(payload\.title \|\| "ChatGPT 通知", payload\.body\)/);
  assert.equal((client.match(/deliverSystemNotification\(/g) || []).length, 3);
  assert.equal((client.match(/setConnectionStatus\(/g) || []).length, 4);
  assert.doesNotMatch(client, /\bsetStatus\(/);
  assert.match(client, /showPageFeedback\("请选择私人文件"\)/);
  assert.match(client, /showPageFeedback\("文件选择已取消"\)/);
  assert.match(client, /showPageFeedback\("上传完成"/);
  assert.match(client, /showPageFeedback\("操作已拦截", payload\.message \|\| "敏感操作已拦截", "error"\)/);
  assert.match(client, /if \(!send\(\{ type: "reload" \}\)\) showPageFeedback\("工作区连接尚未恢复", "", "error"\)/);
  assert.match(client, /setTimeout\(dismissPageFeedback, PAGE_FEEDBACK_MS\)/);
  assert.match(client, /document\.title = `● \$\{workspace\.name\}`/);
  assert.doesNotMatch(server, /notifications\.js/);
  assert.match(client, /payload\.type === "input-target"/);
  assert.match(client, /VIEWER_REPLACED_CLOSE_CODE = 4000/);
  assert.match(client, /当前窗口已停止/);
  assert.match(client, /event\.code === VIEWER_REPLACED_CLOSE_CODE/);
  assert.match(client, /clearTimeout\(reconnectTimer\);\n\s+dismissPageFeedback\(\);/);
  assert.match(client, /crypto\.randomUUID\(\)/);
  assert.match(client, /takeover=\$\{takeover \? "1" : "0"\}/);
  assert.match(client, /if \(socket !== currentSocket\) return/);
  assert.match(client, /reconnectTimer = setTimeout\(connect/);
  assert.match(server, /liveSockets\.add\(user\.id, viewerId, workspaceId, socket, takeover\)/);
  assert.match(server, /broker\.removeViewer\(ownership\.previous\.workspaceId, ownership\.previous\.socket\)/);
  assert.match(server, /ownership\.previous\.socket\.close\(VIEWER_REPLACED_CLOSE_CODE, VIEWER_REPLACED_CLOSE_REASON\)/);
  assert.match(client, /copyClipboardText/);
  assert.match(client, /button: pressedPointerButton\(event\.buttons\)/);
  assert.match(client, /sendPendingPointerMove\(\);\n\s+sendPointer\(event, "mouseReleased"\);\n\s+send\(\{ type: "selection" \}\)/);
  assert.match(textInput, /\["c", "v", "x"\]/);
  assert.match(textInput, /execCommand\("copy"\)/);
  assert.match(cdp, /commands: \["Cut"\]/);
  assert.match(cdp, /clipboardchange/);
  assert.match(cdp, /clipboardQueue/);
  assert.match(cdp, /Browser\.setPermission/);
  assert.match(cdp, /Page\.createIsolatedWorld/);
  assert.match(cdp, /worldName: "gpc-clipboard"/);
  assert.match(client, /viewer-control-panel/);
  assert.match(client, /class: "viewer-toolbar"/);
  assert.match(client, /menuToggle\.setPointerCapture/);
  assert.match(client, /toolbar\.style\.left/);
  assert.match(client, /localStorage\.setItem\(toolbarPositionKey/);
  assert.match(client, /localStorage\.getItem\(toolbarPositionKey\)/);
  assert.match(client, /gpc\.viewerToolbarPosition\.\$\{workspace\.id\}/);
  assert.doesNotMatch(client, /viewer-toolbar-drag|viewer-toolbar-grip|dragHandle/);
  assert.match(client, /viewer-status-icon/);
  assert.match(client, /viewer-menu-icon/);
  assert.match(client, /class: "viewer-toolbar-button viewer-home-button"/);
  assert.match(client, /class: "viewer-toolbar-button viewer-reload-button"/);
  assert.match(client, /"aria-label": "项目首页"/);
  assert.match(client, /"aria-label": "刷新页面"/);
  assert.match(client, /toolbarIcon\(\["M3 11\.5 12 4l9 7\.5"/);
  assert.match(client, /toolbarIcon\(\["M21 12a9 9 0 0 0-15-6\.7L3 8"/);
  assert.doesNotMatch(client, /button\("项目首页"|button\("刷新页面"/);
  assert.match(client, /type: "projectHome"/);
  assert.match(client, /button\("查看文件"/);
  assert.match(client, /button\("进入全屏"/);
  assert.match(client, /button\("退出登录"/);
  assert.match(
    client,
    /upload,\n\s+uploadInput,\n\s+downloads,\n\s+fullscreen,\n\s+logout/,
  );
  assert.match(client, /homeButton,\n\s+reloadButton,\n\s+menuToggle/);
  assert.match(client, /stage,\n\s+pageFeedback,\n\s+toolbar,\n\s+keyCapture/);
  assert.doesNotMatch(client, /button\("文件"|button\("全屏"|button\("退出本地工作区"/);
  assert.match(styles, /\.viewer-toolbar-button/);
  assert.match(styles, /\.viewer-toolbar-icon/);
  assert.match(styles, /\.viewer-feedback/);
  assert.match(styles, /\.viewer-feedback \{[^}]*top: 14px;[^}]*left: 50%;[^}]*transform: translateX\(-50%\);/s);
  assert.doesNotMatch(styles, /\.viewer-feedback \{[^}]*right:/s);
  assert.match(styles, /\.viewer-feedback > span:not\(\.viewer-feedback-close\)[^{]*\{[^}]*overflow-wrap: anywhere;/s);
  assert.match(styles, /@media \(max-width: 560px\) \{\n\s+\.viewer-feedback \{\n\s+top: auto;\n\s+bottom: 14px;/);
  assert.match(styles, /\.viewer-toolbar \{\n\s+position: fixed;\n\s+z-index: 40;\n\s+top: 72px/);
  assert.doesNotMatch(styles, /viewer-toolbar-drag|viewer-toolbar-grip/);
  assert.match(styles, /\.viewer-control-panel \{\n\s+position: absolute;/);
  assert.match(styles, /\.viewer-control-panel \{[^}]*width: min\(300px, calc\(100vw - 28px\)\);[^}]*padding: 10px;/s);
  assert.match(styles, /\.viewer-panel-actions \{[^}]*gap: 6px;/s);
  assert.match(styles, /\.viewer-panel-actions \.button \{[^}]*min-height: 32px;/s);
  assert.match(styles, /\.viewer-transfer-panel \{\n\s+position: absolute;/);
  assert.match(styles, /\.viewer-transfer-storage/);
  assert.match(client, /\u5df2\u7528 \$\{formatBytes\(used\)\} \/ \$\{formatBytes\(quota\)\}/);
  assert.match(client, /\u79c1\u4eba\u6587\u4ef6\u4f1a\u6c38\u4e45\u4fdd\u7559/);
  assert.match(server, /transferStorage: transfers/);
  assert.doesNotMatch(server, /MAX_FILE_BYTES|TRANSFER_QUOTA_BYTES|transferCleanup/);
  assert.doesNotMatch(styles, /object-fit:\s*contain/);
  assert.match(cdp, /MIN_VIEWPORT_WIDTH = 320/);
  assert.match(cdp, /MIN_VIEWPORT_HEIGHT = 240/);
  assert.match(cdp, /windowInsets/);
  assert.match(cdp, /Browser\.setWindowBounds/);
  assert.match(client, /已保存到私人文件区/);
  assert.match(client, /type: "selectFiles"/);
  assert.match(client, /type: "cancelFileSelection"/);
  assert.match(client, /requestId: fileSelection\.requestId/);
  const uploadHandlerStart = client.indexOf('uploadInput.addEventListener("change"');
  const uploadHandlerEnd = client.indexOf('const downloads = button("\u67e5\u770b\u6587\u4ef6"');
  assert.ok(uploadHandlerStart >= 0 && uploadHandlerEnd > uploadHandlerStart);
  const uploadHandler = client.slice(uploadHandlerStart, uploadHandlerEnd);
  assert.doesNotMatch(uploadHandler, /selectFiles|cancelFileSelection/);
  assert.doesNotMatch(client, /attachFiles|upload-armed|upload-attached/);
  assert.doesNotMatch(client, /closePanel = button\("收起"/);
  assert.match(client, /读取 Projects/);
  assert.match(client, /chatgpt-projects\/import/);
  assert.match(client, /operationProgress\("读取 Projects"\)/);
  assert.match(client, /operationProgress\("导入所选"\)/);
  assert.match(client, /readProgress\.set\("running"\)/);
  assert.match(client, /importProgress\.set\("running"\)/);
  assert.match(client, /const labels = \{ idle: "等待开始", running: "进行中", success: "完成", error: "失败" \}/);
  assert.match(client, /textInput\("id", "例如 test"\)/);
  assert.match(client, /textInput\("name", "例如 测试"\)/);
  assert.match(client, /button\("登出"/);
  assert.match(client, /class: "admin-system-panel"/);
  assert.match(client, /orderWorkspaces\(state\.workspaces, state\.workspaceViewers\)/);
  assert.match(client, /class: "workspace-presence"/);
  assert.match(client, /"data-state": presenceState\.state/);
  assert.match(client, /new EventSource\("\/admin\/api\/events"\)/);
  assert.match(client, /orderWorkspaces\(state\.workspaces, live\.workspaceViewers\)/);
  assert.match(client, /href: "\/admin\/maintenance\/"/);
  assert.match(client, /rel: "noopener noreferrer"/);
  assert.match(client, /打开管理员浏览器/);
  assert.match(client, /replace\(shell\("管理", "", content\)\)/);
  assert.match(client, /"details",\n\s+\{ class: "item-card item-details" \}/);
  assert.match(client, /"label",\n\s+\{ class: "project-import-row" \}/);
  assert.match(client, /class: "item-card item-details project-import-results"/);
  assert.match(client, /projectImportResults\.open = false/);
  assert.match(client, /class: "stack admin-item-list"/);
  assert.match(styles, /\.admin-item-list,\n\.project-import-list \{\n  max-height:/);
  assert.match(styles, /\.workspace-presence\[data-state="online"\]/);
  assert.match(server, /workspaceViewers: broker\.viewerCountsByWorkspace\(\)/);
  assert.match(server, /broker\.subscribeState\(broadcastAdminState\)/);
  assert.match(cdp, /subscribeState\(listener\)/);
  assert.doesNotMatch(client, /href: "\/admin\/"/);
  assert.doesNotMatch(client, /button\("退出管理"/);
  assert.doesNotMatch(styles, /\.topbar\s*\{[^}]*border-(?:top|bottom)/);
  assert.doesNotMatch(styles, /\.admin-section\s*\{[^}]*border/);
  assert.doesNotMatch(styles, /\.viewer-panel-heading\s*\{[^}]*border-(?:top|bottom)/);
  assert.match(styles, /\.admin-layout,\n\.stack \{\n  display: grid;\n  grid-template-columns: minmax\(0, 1fr\);/);
  assert.match(client, /document\.title = workspace\.name/);
  assert.doesNotMatch(client, /viewer-bar|viewer-hint/);
  assert.match(textInput, /compositionstart/);
  assert.match(textInput, /compositionend/);
  assert.match(textInput, /insertFromPaste|commitText/);
  assert.match(textInput, /paste: event\.inputType === "insertFromPaste"/);
  assert.match(client, /paste \? \{ paste: true \}/);
  assert.match(textInput, /event\.isComposing/);
  assert.match(textInput, /macOS && event\.metaKey/);
  const index = read("gateway/web/index.html");
  assert.match(index, /<title>GPT Pro<\/title>/);
  assert.match(index, /script type="module"/);
  assert.doesNotMatch(index, /ime\.css/);
  assert.match(read("docker/cdp-fwd.py"), /remote\.settimeout\(None\)/);
  assert.match(read("docker/autostart"), /--disable-backgrounding-occluded-windows/);
  assert.match(read("docker/autostart"), /--disable-renderer-backgrounding/);
  assert.doesNotMatch(read("docker/autostart"), /echo[^\n]*PROXY_URL/);
  assert.doesNotMatch(read("docker/autostart"), /echo[^\n]*START_URL/);
  assert.doesNotMatch(read("docker/proxy-init.sh"), /echo[^\n]*\$\{?RAW/);
  assert.doesNotMatch(read("docker/autostart"), /\. \/config\/\.gpc-proxy/);
});

test("管理员浏览器保留完整 Chromium 界面与扩展管理能力", () => {
  const autostart = read("docker/autostart");
  const openbox = read("docker/update-autostart.sh");
  const dockerfile = read("docker/Dockerfile");
  const compose = read("docker-compose.yml");
  const hideKasm = read("docker/hide-kasm.sh");
  const adminBrowser = read("gateway/web/admin-browser.js");
  const textInput = read("gateway/web/text-input.js");
  const server = read("gateway/server.mjs");
  assert.match(autostart, /--start-maximized/);
  assert.doesNotMatch(autostart, /--kiosk|--start-fullscreen|--app=/);
  assert.match(compose, /NO_DECOR: "1"/);
  assert.doesNotMatch(openbox, /maximized|fullscreen/);
  assert.match(openbox, /\/transfer\/downloads/);
  assert.match(openbox, /default_directory/);
  assert.doesNotMatch(dockerfile, /fcitx/);
  assert.doesNotMatch(autostart, /fcitx|GTK_IM_MODULE|XMODIFIERS/);
  assert.match(hideKasm, /__gpc\/admin-browser\.js/);
  assert.match(hideKasm, /<title>GPT Pro<\/title>/);
  assert.doesNotMatch(hideKasm, /<title>ChatGPT<\/title>/);
  assert.match(adminBrowser, /noVNC_setting_enable_ime/);
  assert.match(adminBrowser, /installAdministratorPaste/);
  assert.match(adminBrowser, /installAdministratorDownloads/);
  assert.match(adminBrowser, /new EventSourceCtor\("\/__gpc\/download-events"\)/);
  assert.match(adminBrowser, /link\.href = `\/__gpc\/files\/\$\{encodeURIComponent\(file\.id\)\}`/);
  assert.match(adminBrowser, /event\.clipboardData\?\.getData\("text\/plain"\)/);
  assert.match(adminBrowser, /clipboardInput\.dispatchEvent\(new EventCtor\("change"/);
  assert.match(adminBrowser, /code: "KeyV", ctrlKey: true/);
  assert.match(textInput, /shouldForwardKey/);
  assert.doesNotMatch(server, /api\/ime\/candidates|pinyin/);
});
