import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const read = (file) => readFileSync(new URL(`../${file}`, import.meta.url), "utf8");

test("Compose 只保留一个桌面 Profile 且不挂 Docker Socket", () => {
  const compose = read("docker-compose.yml");
  assert.match(compose, /desktop:\n/);
  assert.match(compose, /\.\/data\/browser:\/config/);
  assert.match(compose, /GPC_CDP_ALLOW:/);
  assert.match(compose, /PROFILE_AUTO_DETECT:/);
  assert.match(compose, /PROFILE_GEO_ENDPOINT:/);
  assert.match(compose, /FRAME_ACTIVE_FPS:/);
  assert.match(compose, /\.\/data-transfer:\/transfer/g);
  assert.doesNotMatch(compose, /docker\.sock/);
  assert.equal((compose.match(/^  desktop:\s*$/gm) || []).length, 1);
});

test("Docker 构建上下文排除凭据、Profile 与实验产物", () => {
  const ignored = read(".dockerignore");
  for (const path of [".env", "data", "data-panel", "data-transfer", "tmp", "node_modules"]) {
    assert.match(ignored, new RegExp(`^${path.replace(".", "\\.")}$`, "m"));
  }
});

test("启动脚本只在容器健康后打印入口", () => {
  const script = read("scripts/up.sh");
  assert.match(script, /docker compose up -d --build --wait/);
  assert.ok(script.indexOf("--wait") < script.indexOf('echo "入口：'));
});

test("云开发预览使用动态状态且没有内置回退密码", () => {
  const cursor = read(".cursor/environment.json");
  assert.doesNotMatch(cursor, /devpass|cd gateway/);
  assert.match(cursor, /data-panel\/state\.json/);
});

test("业务代码使用动态工作区路径 Cookie", () => {
  const server = read("gateway/server.mjs");
  assert.match(server, /Path=\$\{path\}/);
  assert.match(server, /workspaceId/);
});

test("网关通过 CDP sessionId 定向输入、文件和独立窗口连续流", () => {
  const pkg = JSON.parse(read("package.json"));
  assert.ok(pkg.dependencies.ws);
  const cdp = read("lib/cdp.mjs");
  assert.match(cdp, /Input\.insertText/);
  assert.match(cdp, /sessionId/);
  assert.match(cdp, /Target\.createTarget/);
  assert.match(cdp, /gpc\.workspaceId/);
  assert.match(cdp, /sessionStorage\.setItem/);
  assert.match(cdp, /Emulation\.setTimezoneOverride/);
  assert.match(cdp, /Emulation\.setLocaleOverride/);
  assert.doesNotMatch(cdp, /Network\.setExtraHTTPHeaders/);
  assert.match(cdp, /Network\.setBlockedURLs/);
  assert.match(cdp, /Network\.getResponseBody/);
  assert.match(cdp, /listChatGptProjects/);
  assert.doesNotMatch(cdp, /Fetch\./);
  assert.match(cdp, /DOM\.setFileInputFiles/);
  assert.match(cdp, /Page\.fileChooserOpened/);
  assert.match(cdp, /fileChooserOwner/);
  assert.match(cdp, /command\.type === "selectFiles"/);
  assert.match(cdp, /command\.type === "cancelFileSelection"/);
  assert.match(cdp, /resolveUserUploads/);
  assert.doesNotMatch(cdp, /attachFiles|pendingUploads|input\[type='file'\]/);
  assert.match(cdp, /Browser\.setDownloadBehavior/);
  assert.match(cdp, /Page\.startScreencast/);
  assert.match(cdp, /Page\.screencastFrameAck/);
  assert.match(cdp, /globalThis\[binding\]\(""\)/);
  assert.match(cdp, /captureMode: "target-screencast"/);
  assert.match(cdp, /newWindow: true/);
  assert.doesNotMatch(cdp, /Page\.captureScreenshot/);
  assert.match(cdp, /activeFrameFps/);
  assert.match(cdp, /SCREENCAST_TIERS/);
  assert.match(cdp, /streamTier/);
  assert.doesNotMatch(cdp, /Target\.activateTarget/);
  assert.match(cdp, /userAgentMetadata/);
  const focus = read("lib/focus.mjs");
  const policy = read("lib/policy.mjs");
  assert.match(focus, /projectNavigationAllowed/);
  assert.match(focus, /aside\[aria-label\*="sidebar" i\]/);
  assert.match(focus, /create-new-chat-button/);
  assert.match(focus, /button\[role="radio"\]/);
  assert.match(focus, /share-chat-button/);
  assert.match(focus, /share-chat-menu-item/);
  assert.match(focus, /share-prompt-link-turn-action-button/);
  assert.doesNotMatch(focus, /copy-turn-action-button/);
  assert.doesNotMatch(focus, /conversation-options-button/);
  assert.match(focus, /Show project details/);
  assert.match(focus, /move to project/);
  assert.match(focus, /remove from project/);
  assert.match(policy, /data-gpc-sensitive-hidden/);
  assert.doesNotMatch(focus, /stopImmediatePropagation|preventDefault/);
  assert.doesNotMatch(policy, /stopImmediatePropagation|preventDefault/);
  const client = read("gateway/web/app.js");
  const styles = read("gateway/web/app.css");
  const textInput = read("gateway/web/text-input.js");
  assert.match(client, /type: "viewerState"/);
  assert.match(client, /visibilitychange/);
  assert.match(client, /attachNativeTextInput/);
  assert.match(client, /type: "selection"/);
  assert.match(client, /type: "cut"/);
  assert.match(client, /payload\.type === "clipboard"/);
  assert.match(client, /payload\.type === "input-target"/);
  assert.match(client, /copyClipboardText/);
  assert.match(client, /button: pressedPointerButton\(event\.buttons\)/);
  assert.match(client, /sendPendingPointerMove\(\);\n\s+sendPointer\(event, "mouseReleased"\);\n\s+send\(\{ type: "selection" \}\)/);
  assert.match(textInput, /\["c", "v", "x"\]/);
  assert.match(textInput, /execCommand\("copy"\)/);
  assert.match(cdp, /commands: \["Cut"\]/);
  assert.match(cdp, /clipboardchange/);
  assert.match(cdp, /clipboardQueue/);
  assert.match(cdp, /Browser\.setPermission/);
  assert.match(cdp, /Page\.createIsolatedWorld/);
  assert.match(cdp, /worldName: "gpc-clipboard"/);
  assert.match(client, /viewer-control-panel/);
  assert.match(client, /viewer-status-icon/);
  assert.match(client, /viewer-menu-icon/);
  assert.match(client, /button\("项目首页"/);
  assert.match(client, /type: "projectHome"/);
  assert.match(client, /button\("查看文件"/);
  assert.match(client, /button\("进入全屏"/);
  assert.match(client, /button\("退出登录"/);
  assert.match(
    client,
    /viewer-panel-actions" \}, upload, uploadInput, downloads, fullscreen, reload, logout/,
  );
  assert.match(client, /stage, homeButton, menuToggle, controlPanel/);
  assert.doesNotMatch(client, /button\("文件"|button\("全屏"|button\("退出本地工作区"/);
  assert.match(styles, /\.viewer-home-button/);
  assert.doesNotMatch(styles, /object-fit:\s*contain/);
  assert.match(cdp, /MIN_VIEWPORT_WIDTH = 320/);
  assert.match(cdp, /MIN_VIEWPORT_HEIGHT = 240/);
  assert.match(cdp, /windowInsets/);
  assert.match(cdp, /Browser\.setWindowBounds/);
  assert.match(client, /已保存到私人文件区/);
  assert.match(client, /type: "selectFiles"/);
  assert.match(client, /type: "cancelFileSelection"/);
  const uploadHandlerStart = client.indexOf('uploadInput.addEventListener("change"');
  const uploadHandlerEnd = client.indexOf('const downloads = button("\u67e5\u770b\u6587\u4ef6"');
  assert.ok(uploadHandlerStart >= 0 && uploadHandlerEnd > uploadHandlerStart);
  const uploadHandler = client.slice(uploadHandlerStart, uploadHandlerEnd);
  assert.doesNotMatch(uploadHandler, /selectFiles|cancelFileSelection/);
  assert.doesNotMatch(client, /attachFiles|upload-armed|upload-attached/);
  assert.doesNotMatch(client, /closePanel = button\("收起"/);
  assert.match(client, /读取 Projects/);
  assert.match(client, /chatgpt-projects\/import/);
  assert.match(client, /operationProgress\("读取 Projects"\)/);
  assert.match(client, /operationProgress\("导入所选"\)/);
  assert.match(client, /readProgress\.set\("running"\)/);
  assert.match(client, /importProgress\.set\("running"\)/);
  assert.match(client, /const labels = \{ idle: "等待开始", running: "进行中", success: "完成", error: "失败" \}/);
  assert.match(client, /textInput\("id", "例如 test"\)/);
  assert.match(client, /textInput\("name", "例如 测试"\)/);
  assert.match(client, /button\("登出"/);
  assert.match(client, /class: "admin-system-panel"/);
  assert.match(client, /href: "\/admin\/maintenance\/"/);
  assert.match(client, /打开管理员浏览器/);
  assert.match(client, /replace\(shell\("管理", "", content\)\)/);
  assert.match(client, /"details",\n\s+\{ class: "item-card item-details" \}/);
  assert.match(client, /"label",\n\s+\{ class: "project-import-row" \}/);
  assert.match(client, /class: "item-card item-details project-import-results"/);
  assert.match(client, /projectImportResults\.open = false/);
  assert.match(client, /class: "stack admin-item-list"/);
  assert.match(styles, /\.admin-item-list,\n\.project-import-list \{\n  max-height:/);
  assert.doesNotMatch(client, /href: "\/admin\/"/);
  assert.doesNotMatch(client, /button\("退出管理"/);
  assert.doesNotMatch(styles, /\.topbar\s*\{[^}]*border-(?:top|bottom)/);
  assert.doesNotMatch(styles, /\.admin-section\s*\{[^}]*border/);
  assert.doesNotMatch(styles, /\.viewer-panel-heading\s*\{[^}]*border-(?:top|bottom)/);
  assert.match(styles, /\.admin-layout,\n\.stack \{\n  display: grid;\n  grid-template-columns: minmax\(0, 1fr\);/);
  assert.match(client, /document\.title = workspace\.name/);
  assert.doesNotMatch(client, /viewer-bar|viewer-hint/);
  assert.match(textInput, /compositionstart/);
  assert.match(textInput, /compositionend/);
  assert.match(textInput, /insertFromPaste|commitText/);
  assert.match(textInput, /paste: event\.inputType === "insertFromPaste"/);
  assert.match(client, /paste \? \{ paste: true \}/);
  assert.match(textInput, /event\.isComposing/);
  assert.match(textInput, /macOS && event\.metaKey/);
  const index = read("gateway/web/index.html");
  assert.match(index, /<title>GPT Pro<\/title>/);
  assert.match(index, /script type="module"/);
  assert.doesNotMatch(index, /ime\.css/);
  assert.match(read("docker/cdp-fwd.py"), /remote\.settimeout\(None\)/);
  assert.match(read("docker/autostart"), /--disable-backgrounding-occluded-windows/);
  assert.match(read("docker/autostart"), /--disable-renderer-backgrounding/);
  assert.doesNotMatch(read("docker/autostart"), /echo[^\n]*PROXY_URL/);
  assert.doesNotMatch(read("docker/autostart"), /echo[^\n]*START_URL/);
  assert.doesNotMatch(read("docker/proxy-init.sh"), /echo[^\n]*\$\{?RAW/);
  assert.doesNotMatch(read("docker/autostart"), /\. \/config\/\.gpc-proxy/);
});

test("管理员浏览器保留完整 Chromium 界面与扩展管理能力", () => {
  const autostart = read("docker/autostart");
  const openbox = read("docker/update-autostart.sh");
  const dockerfile = read("docker/Dockerfile");
  const compose = read("docker-compose.yml");
  const hideKasm = read("docker/hide-kasm.sh");
  const adminBrowser = read("gateway/web/admin-browser.js");
  const textInput = read("gateway/web/text-input.js");
  const server = read("gateway/server.mjs");
  assert.match(autostart, /--start-maximized/);
  assert.doesNotMatch(autostart, /--kiosk|--start-fullscreen|--app=/);
  assert.match(compose, /NO_DECOR: "1"/);
  assert.doesNotMatch(openbox, /maximized|fullscreen/);
  assert.match(openbox, /\/transfer\/downloads/);
  assert.match(openbox, /default_directory/);
  assert.doesNotMatch(dockerfile, /fcitx/);
  assert.doesNotMatch(autostart, /fcitx|GTK_IM_MODULE|XMODIFIERS/);
  assert.match(hideKasm, /__gpc\/admin-browser\.js/);
  assert.match(hideKasm, /<title>GPT Pro<\/title>/);
  assert.doesNotMatch(hideKasm, /<title>ChatGPT<\/title>/);
  assert.match(adminBrowser, /noVNC_setting_enable_ime/);
  assert.match(textInput, /shouldForwardKey/);
  assert.doesNotMatch(server, /api\/ime\/candidates|pinyin/);
});
